import * as THREE from 'three';
import { GLTF } from 'three-stdlib';

export interface ParticlesType {
  geometry: THREE.BufferGeometry;
  material: THREE.ShaderMaterial;
  count: number;
  positions: THREE.Float32BufferAttribute[];
  index: number;
  maxCount: number;
  colorA: string;
  colorB: string;
  morph?: (index: number) => void;
}

export type GLTFResult = GLTF & {
  nodes: {
    Body_1: THREE.SkinnedMesh;
    Body_2: THREE.SkinnedMesh;
    Body_3: THREE.SkinnedMesh;
    Body_4: THREE.SkinnedMesh;
    Body_5: THREE.SkinnedMesh;
    Body_6: THREE.SkinnedMesh;
    Body_7: THREE.SkinnedMesh;
    Head: THREE.Bone;
    Trinket: THREE.Mesh;
    Macbook001: THREE.Mesh;
    Macbook001_1: THREE.Mesh;
    Macbook001_2: THREE.Mesh;
    Macbook001_3: THREE.Mesh;
    Macbook001_4: THREE.Mesh;
    Macbook001_5: THREE.Mesh;
    Macbook001_6: THREE.Mesh;
    Macbook001_7: THREE.Mesh;
    Macbook001_8: THREE.Mesh;
    iPad: THREE.Group;
    iPad001: THREE.Mesh;
    iPad001_1: THREE.Mesh;
    iPad001_2: THREE.Mesh;
    iPad001_3: THREE.Mesh;
    iPad001_4: THREE.Mesh;
    iPad001_5: THREE.Mesh;
    iPad001_6: THREE.Mesh;
    iPad001_7: THREE.Mesh;
    iPad001_8: THREE.Mesh;
    iPad001_9: THREE.Mesh;
    iPad001_10: THREE.Mesh;
    iPad001_11: THREE.Mesh;
    iPad001_12: THREE.Mesh;
    iPad001_13: THREE.Mesh;
    Hips: THREE.Bone;
  };
  materials: {
    ['Body.001']: THREE.MeshPhysicalMaterial;
    Outfit_Bottom: THREE.MeshStandardMaterial;
    Outfit_Footwear: THREE.MeshStandardMaterial;
    Outfit_Top: THREE.MeshStandardMaterial;
    Skin: THREE.MeshStandardMaterial;
    Eye: THREE.MeshStandardMaterial;
    Hair: THREE.MeshStandardMaterial;
    ['Trinket.001']: THREE.MeshStandardMaterial;
    ['Top.001']: THREE.MeshStandardMaterial;
    ['Rubber.001']: THREE.MeshStandardMaterial;
    ['AppleLogo.001']: THREE.MeshStandardMaterial;
    ['Bottom.001']: THREE.MeshStandardMaterial;
    ['UsbCInside.001']: THREE.MeshStandardMaterial;
    ['Legs.001']: THREE.MeshStandardMaterial;
    ['HingeBlack.001']: THREE.MeshStandardMaterial;
    ['HeadPhoneHole.001']: THREE.MeshStandardMaterial;
    ['bezel.001']: THREE.MeshStandardMaterial;
    ['Body.003']: THREE.MeshStandardMaterial;
    ['Line.001']: THREE.MeshStandardMaterial;
    ['material.001']: THREE.MeshStandardMaterial;
    ['cameraframe_and_logo.001']: THREE.MeshStandardMaterial;
    ['camera12.001']: THREE.MeshStandardMaterial;
    ['front_camera.001']: THREE.MeshStandardMaterial;
    ['glass.001']: THREE.MeshStandardMaterial;
    ['camera1.001']: THREE.MeshStandardMaterial;
    ['camera2.002']: THREE.MeshStandardMaterial;
    ['Camera_Flash.001']: THREE.MeshStandardMaterial;
    ['camera2.003']: THREE.MeshStandardMaterial;
    ['LiDar.001']: THREE.MeshStandardMaterial;
  };
};
